var TEXT_SCORE     = "SCORE";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_GAMEOVER = "CONGRATULATION! YOU WON THIS MATCH!";
var TEXT_WIN  = "%s WON THIS MATCH";
var TEXT_PLAYER = "PLAYER %s";
var TEXT_AI = "AI";
var TEXT_SELECT_PLAYERS_MENU = "SELECT MODE";
var TEXT_NO_MOVES_AVAILABLE = "NO MOVES AVAILABLE, NEXT PLAYER WILL PLAY";
var TEXT_DOUBLE_DICES = "GOT A DOUBLE, DICES REDOUBLED";
var TEXT_THINKING = "THINKING";
var TEXT_WAITING_MOVES = "WAITING OPPONENT";

var TEXT_RULEBROKEN_BOTH = "WITH THIS MOVE YOU CAN'T PLAY ALL DICES. PLEASE DO ANOTHER MOVES THAT ALLOWS YOU PLAY BOTH DICES";
var TEXT_RULEBROKEN_HIGHER = "WITH THIS MOVE YOU CAN'T PLAY THE DICE WITH HIGHER VALUE. PLEASE DO ANOTHER MOVE THAT ALLOWS YOU TO DO IT";